version: 0.1.0.{build}
image: Visual Studio 2017 RC
configuration:
- Release
- Debug
platform: Any CPU
assembly_info:
  patch: true
  file: '**\AssemblyInfo.*'
  assembly_version: '{version}'
  assembly_file_version: '{version}'
  assembly_informational_version: '{version}'
before_build:
- cmd: >-
    set PATH=C:\Program Files (x86)\MSBuild\15.0\Bin;%PATH%

    nuget restore
build:
  project: Winston.sln
  parallel: true
  verbosity: normal
test_script:
- ps: .\tests.ps1 $env:CONFIGURATION
artifacts:
- path: winston_install\*\winston_install.exe
  name: Installer
deploy: off