version: 0.1.0.{build}
image: Visual Studio 2015
configuration:
- Release
- Debug
platform: Any CPU
assembly_info:
  patch: true
  file: '**\AssemblyInfo.*'
  assembly_version: '{version}'
  assembly_file_version: '{version}'
  assembly_informational_version: '{version}'
before_build:
- cmd: >-
    set PATH=C:\Program Files (x86)\MSBuild\14.0\Bin;%PATH%

    nuget restore
build:
  project: Winston.sln
  parallel: true
  verbosity: normal
test_script:
- ps: .\tests.ps1 $env:CONFIGURATION
artifacts:
- path: winston_install\*\winston_install.exe
  name: Installer
deploy:
- provider: GitHub
  tag: v$(appveyor_build_version)
  release: Winston v$(appveyor_build_version)
  auth_token:
    secure: w+t0wzywwZ+lkCEM0C02sbug8hyng0w4vm5DLUhYu7eKI2ysVEC5pmhNAk5dLMsT
  artifact: winston_install\Release\winston_install.exe
  draft: true
  prerelease: true
  force_update: true